FROM debian:buster-slim

ENV GODEBUG netdns=go

# Install required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates unzip groff curl sudo && \
    rm -rf /var/lib/apt/lists/*

ADD release/linux/arm64/plugin /bin/
ENTRYPOINT ["/bin/plugin"]
